name: "Release"

on:
  push:
    tags:
      - "v*"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'zulu'
        
      - name: Setup Gradle
        uses: gradle/gradle-build-action@v3.4.2
      
      - name: Execute Gradle build
        run: ./gradlew jar

      - uses: actions/upload-artifact@v3
        with:
          name: Package JAR
          path: build/libs

      - name: publish release
        uses: marvinpinto/action-automatic-releases@latest
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          files: build/libs/EntityCC-*-Beta.jar
          prerelease: false